alphagov/paste-html-to-govspeak

- test/main.test.js
These are a bit hairy for dealing with the DOM and whatever JSDOM has
set up.
document.execCommand is mocked as per the suggestion in
https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom
> Create integration test for main method

- examples/debug.html
This uses the [js-beautify library][1] to style the HTML that is
debugged to make it easier to read. It still has style attributes which
are the hardest part to read. I'm not too sure of a simple way to remove
them though or if we even should.
It sets a pre-wrap on the pre elements so they're easier to read without
scroll. However as HTML has massive style attributes and wrapped
prettifying this is still white-space: pre for scrolling.
[1]: https://github.com/beautify-web/js-beautify
> Make HTML easier to read in debug

- examples/debug.html
This try catch was failing in IE because of the lack of argument. This
also logs the error for good measure.
> Catch errors properly in IE

- src/to-govspeak.js
- test/to-govspeak.test.js
Trello: https://trello.com/c/P5KBetGh/754-resolve-issues-identified-from-copy-and-paste-testing
See commits for details
> Fix google docs lists

- src/to-govspeak.js
- test/to-govspeak.test.js
Trello: https://trello.com/c/P5KBetGh/754-resolve-issues-identified-from-copy-and-paste-testing
This was a rather hard problem to solve, so brace yourself as this
message might be complex.
We were having cases of HTML pasted from browsers adding span elements in
for spaces. So we could end up with HTML like:
`Some text<span> </span><a href="">Link</a>` where, depending on the
environment, the contents of the span could be `<span>&nbsp;</span>` or
`<span> </span>`. In browsers it was the former.
This causes some poor behaviour in turndown where the presence of a
nbsp; character (which has an ASCII code of 160) causes the whole space
to be stripped out, resulting in `Some text[Link]()` as output. On the
other hand the presence of a normal space (ASCII code 32) causes a
different problem of …
>  Fix the mysterious case of spaces being removed

- .travis.yml
https://trello.com/c/e1AYHybj/672-put-together-the-copy-and-paste-work-as-a-package-that-can-be-included
This configures Travis to automatically push a new tagged version when
the package version in package.json changes, as well as push the new
version to NPM if it isn't already there. We use different checks for
each function to ensure they can run independently if one of them fails.
> Auto-tag and publish to NPM via Travis

- .travis.yml
https://trello.com/c/e1AYHybj/672-put-together-the-copy-and-paste-work-as-a-package-that-can-be-included
Previously we were trying to push a tag if it already existed, instead
of if it did not exist.
> Fix tag deploy test (invert flag)

- CHANGELOG.md
- src/html-to-govspeak.js
- test/html-to-govspeak.test.js
Trello: https://trello.com/c/Fhqmp62n/771-document-outcome-of-testing-paste-html-to-govspeak
GOV.UK supports h2 and h3 headers (with h4 allowed but discouraged). h1
headers are reserved for the page title. Previously this was supported
by stripping h1, h4, h5, and h6 headers.
A product decision has been made that instead of stripping h1, h4 and h5
elements these are converted to h2 or h3s, so that they are preserved of
headers but lose some of their hierarchical meaning.
> Convert headers to h2 or h3 rather than strip

- CHANGELOG.md
- src/html-to-govspeak.js
- test/html-to-govspeak.test.js
Trello: https://trello.com/c/Fhqmp62n/771-document-outcome-of-testing-paste-html-to-govspeak
This removes some elements that weren't being removed by default and iterates the syntax for removing elements.
This also fixes a common situation where pasting leads to a bunch of preceding whitespace. I identified that this was caused by elements in `<head>` that are removed interacting with the first visible element. This can be resolved rather simply by trimming the govspeak being output.
> Improve element removal and remove preceding whitespace

- CHANGELOG.md
- src/html-to-govspeak.js
- test/__fixtures__/word-2016-comments.html
- test/html-to-govspeak.test.js
Trello: https://trello.com/c/3JX1Pc9f/770-embed-paste-html-to-govspeak-functionality
When users add comments to Word 2016 documents and then copy that
content the word document contains the comments that are output.
This commit removes these comments. It does this by matching the
particular element and class name combinations produced by Microsoft
Word.
This is likely very delicate as it requires MS Office to consistently
produce the same code even in future versions.
The HTML snippet to test this was rather big for testing an individual
scenario so I decided to create a fixture for this and include the full
HTML that is output. After chatting with Alex a directory of
__fixtures__ was deemed a common JS library convention.
>  Remove Microsoft Word comments

- examples/index.html
- examples/input.html
This updates the input example to match the headers and pre support we have
It changes the example page to output raw and formatted HTML. Although formatted HTML is much easier to read subtle differences between this and the raw HTML can produce different outcomes.
> Update example files

- CHANGELOG.md
- src/html-to-govspeak.js
- test/__fixtures__/word-2016-comments.html
- test/__fixtures__/word-2016-nested-list.html
- test/__fixtures__/word-2016-ordered-list.html
- test/__fixtures__/word-2016-unordered-list.html
- test/html-to-govspeak.test.js
Trello: https://trello.com/c/Fhqmp62n/771-document-outcome-of-testing-paste-html-to-govspeak
This parses the HTML that Microsoft Word produces for lists and
converts this to markdown.
It has to rely on parsing class names and style attributes, so is very
fragile for any iterations that Microsoft make to this. Hopefully future
versions may use actual HTML list markup so this may not be needed.
Lists are presented in a series of paragraphs with the first item having
a class of "MsoListParagraphCxSpFirst", the last item having a class of
"MsoListParagraphCxSpLast" and all the other list items having a class
of "MsoListParagraphCxSpMiddle". This behaviour is regardless of whether
there are nested lists or not.
Whether an item is nested in a list or not can be determined by a style
property of …
> Convert Microsoft Word lists to markdown lists

- CHANGELOG.md
- src/html-to-govspeak.js
- test/html-to-govspeak.test.js
Trello: https://trello.com/c/Fhqmp62n/771-document-outcome-of-testing-paste-html-to-govspeak
So shortly after releasing the Word list HTML conversion I found some
documents opened in word that didn't behave the same as the other ones I
tested (le sigh).
Looking at the HTML that was produced there showed a lack of list class
names and instead usage of the MsoNormal class (which Word normally uses
for paragraphs).
It wasn't too hard to change the code we have now to handle both of
these scenarios so I've updated it for this.
> Widen support of Word HTML lists

- CHANGELOG.md
- src/html-to-govspeak.js
- test/html-to-govspeak.test.js
Trello: https://trello.com/c/7pL98HiY/780-investigate-chrome-address-bar-copy-and-paste-issue
Pasting from the address bar in Google Chrome produces a HTML output of
the link, for example going to
`https://alphagov.github.io/paste-html-to-govspeak/` and then selecting the
address bar and copying will produce HTML of:
<meta charset='utf-8'><a href="https://alphagov.github.io/paste-html-to-govspeak/">https://alphagov.github.io/paste-html-to-govspeak/</a>
This causes a real problem in one of the use cases of this tool: when
users are embedding a link into their content and paste it from the
address bar.
The approach to solve this is to strip links in the following scenario:
- When link text matches link content
- When the link content is the same as the body of the HTML document
> Strip links that seem to be pasted from address bar

- CHANGELOG.md
- package-lock.json
- package.json
Trello: https://trello.com/c/7pL98HiY/780-investigate-chrome-address-bar-copy-and-paste-issue
This bumps the version for release and updates NPM dependencies that are flagged as having vulnerabilities.
> Bump to version 0.2.2

- src/legacy-html-from-paste.js
- test/legacy-html-from-paste.test.js
We check for write access to clipboard before trying to take the legacy approach, otherwise we run into a bug where we're not allowed by the browser to paste in a `contenteditable` container (which is the workaround used in this approach) when the user declines access to clipboard or the "Programmatic clipboard access" is disabled in Internet Options in IE.
This solution have been tested in the following scenarios:
- Paste into our input and the clipboard data is preserved
- Paste into our input and then on another web page and both times the clipboard data is preserved
- Paste into our input and then into another application (Notepad) and both times the clipboard data is preserved
[Trello card](https://trello.com/c/YUzyMrrn)
> Check for clipboard access on the 'legacy' approach

- CHANGELOG.md
- package-lock.json
- package.json
- Fix error when pasting content at the end of the textarea in IE11 by updating insert-text-at-cursor to 0.3.0 (PR #53)
- Fix paste action when access to clipboard is disabled in IE11 (PR #52)
> Release 0.2.3

- CHANGELOG.md
- package-lock.json
- package.json
- src/html-to-govspeak.js
- src/legacy-html-from-paste.js
- src/main.js
- test/html-to-govspeak.test.js
This releases the 3 security PRs that were merged earlier today (https://github.com/alphagov/paste-html-to-govspeak/pull/56, https://github.com/alphagov/paste-html-to-govspeak/pull/57, https://github.com/alphagov/paste-html-to-govspeak/pull/58) and updates the other dependencies.
It also has some linting fixes for the Standard 12 -> 14 release.
> Bump dependencies for 0.2.4

- .travis.yml
Travis is currently raising errors stating that an API key is missing.
This is because of an issue at travis [1] which can be resolved with this
edge: true [2] argument to opt into new behaviour.
[1]: https://travis-ci.community/t/missing-api-key-when-deploying-to-github-releases/5761/8
[2]: https://docs.travis-ci.com/user/deployment-v2#how-to-opt-in-to-v2
> Set edge true to travis deploys

- .babelrc
- package.json
Babel has recently dropped IE11 support.
This change ensures that we target IE11 specifically as well as the defaults supported by Babel.
Needed for #235
> Ensure IE 11 support

- CHANGELOG.md
- package-lock.json
- package.json
- src/html-to-govspeak.js
- test/html-to-govspeak.test.js
Currently the Paste to Govspeak converter (paste-html-to-govspeak) in the publishing applications automatically converts any H4s, H5s and H6s to a H3.
We want to remove this functionality and allow H4s, H5s and H6s without them being converted to H3s.
This change allows all headers from h2 to h6.
Although GOV.UK doesn't style H4s and below (in non-HTML attachments), it's important for users using assistive technology get the correct heading structure.
https://trello.com/c/aWGmHS2s/573-allow-h4s-to-h6s-with-paste-to-govspeak-converter
> Allow H4s to H6s with Paste to Govspeak converter

- .github/dependabot.yml
We don't need to be updating this every day or even week. As far as I
can tell from the docs [1] this also won't prevent security updates.
[1]: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval
> Check for dependabot monthly

- src/html-to-govspeak.js
- src/tables.js
- test/__fixtures__/google-docs-2023-table.html
- test/html-to-govspeak.test.js
This PR adds a Turndown plugin which can convert tables from HTML to Govspeak markdown tables.
The tables implementation is copied from https://github.com/mixmark-io/turndown-plugin-gfm/blob/master/src/tables.js, but I had to make it more permissive because the original was too pernickety about the existence of a table header to work with tables copied from LibreOffice or Google Docs/Sheets.
I have tested this with Google Docs, Sheets, and LibreOffice Documents. I don't have access to MS Word but I assume this is what publishers use most often, so it would be good to test with that too.
The plugin does not support the row title feature ([see docs](https://www.gov.uk/guidance/how-to-publish-on-gov-uk/markdown)) as it isn't possible to tell when a row heading shouldn't be used …
> Add table plugin for turndown

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/html-to-govspeak.js
- test/html-to-govspeak.test.js
Our guidance is for email links to be the email address wrapped in less than / greater than arrows:
https://www.gov.uk/guidance/how-to-publish-on-gov-uk/markdown#:~:text=admin/publications/123456.-,Email%20links,-Use%20%E2%80%98less%20than
Prior to this commit, paste-html-to-govspeak would output normal markdown links instead, i.e.
`[example@example.com](mailto:example@example.com)`
Trello: https://trello.com/c/w38PbWxD/
> Version 0.5.0: fixes to email link markdown
